language: python

python:
  - "3.4"

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=django_project.settings_prod
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE USER django WITH password 'j2sYlTGz45';" -U postgres
  - psql -c "ALTER USER django CREATEDB;" -U postgres

script:
  - python manage.py test